export const CONFIG = {
  CANVAS_WIDTH: 960,
  CANVAS_HEIGHT: 540,
  WORLD_RADIUS: 5000,

  PLAYER_RADIUS: 15,
  PLAYER_BASE_HP: 100,
  PLAYER_BASE_MOVE_SPEED: 220,
  PLAYER_BASE_FIRE_RATE: 3.0,
  PLAYER_BASE_BULLET_RANGE: 650,
  PLAYER_BASE_DAMAGE: 12,

  BULLET_SPEED: 600,
  BULLET_RADIUS: 4,

  ENEMY_RADIUS: 16,
  ENEMY_BASE_SPEED: 70,
  ENEMY_BASE_HP: 30,
  ENEMY_DAMAGE: 10,

  BOSS_RADIUS: 32,
  BOSS_HP_MULT: 10,
  BOSS_SPEED_MULT: 0.7,

  BOOSTER_CRIT_COLOR: "#30d7ff",
  BOOSTER_UTILITY_COLOR: "#30ff88",
  BOSS_COLOR: "#e045ff",
  ENEMY_COLOR: "#ff4040",

  PICKUP_RADIUS: 10,
  PICKUP_HEAL_AMOUNT: 15,

  BOOSTER_CRIT_CHANCE_ADD: 0.10,
  BOOSTER_CRIT_DAMAGE_ADD: 0.50,
  BOOSTER_CRIT_DURATION: 180,

  BOOSTER_UTILITY_FIRE_ADD: 0.20,
  BOOSTER_UTILITY_RANGE_ADD: 0.20,
  BOOSTER_UTILITY_SPEED_ADD: 0.10,
  BOOSTER_UTILITY_DURATION: 60,

  MAX_PERM_CRIT_CHANCE: 0.70,
  MAX_TOTAL_CRIT_CHANCE: 0.90,

  BASE_CRIT_CHANCE: 0.0,
  BASE_CRIT_MULT: 2.0,

  WAVE_BASE_ENEMIES: 6,
  WAVE_ENEMY_GROWTH: 1.3,
  WAVE_BOSS_INTERVAL: 3,

  BOOSTER_MIN_INTERVAL: 15,
  BOOSTER_RANDOM_CHANCE: 0.45,

  PICKUP_MAGNET_BASE: 90,
  PICKUP_MAGNET_PER_WAVE: 12,
};
