export const CONFIG = {
  CANVAS_WIDTH: 960,
  CANVAS_HEIGHT: 540,

  WORLD_RADIUS: 4500,

  PLAYER_RADIUS: 14,
  PLAYER_BASE_HP: 100,
  PLAYER_BASE_MOVE_SPEED: 220,
  PLAYER_BASE_FIRE_RATE: 3.0,
  PLAYER_BASE_BULLET_RANGE: 650,
  PLAYER_BASE_DAMAGE: 12,

  BULLET_SPEED: 620,
  BULLET_RADIUS: 4,

  ROCKET_SPEED: 380,
  ROCKET_RADIUS: 6,
  ROCKET_EXPLOSION_RADIUS: 120,
  ROCKET_DIRECT_MULT: 1.4,
  ROCKET_SPLASH_MULT: 0.7,

  ENEMY_RADIUS: 15,
  ENEMY_BASE_SPEED: 70,
  ENEMY_BASE_HP: 34,
  ENEMY_CONTACT_DMG: 22,

  BOSS_RADIUS: 30,
  BOSS_HP_MULT: 10,
  BOSS_SPEED_MULT: 0.7,

  PICKUP_RADIUS: 9,
  PICKUP_HEAL_AMOUNT: 20,

  BOOSTER_CRIT_CHANCE_ADD: 0.20,
  BOOSTER_CRIT_DAMAGE_ADD: 0.50,
  BOOSTER_CRIT_DURATION: 180,

  BOOSTER_UTILITY_FIRE_ADD: 0.20,
  BOOSTER_UTILITY_RANGE_ADD: 0.20,
  BOOSTER_UTILITY_SPEED_ADD: 0.10,
  BOOSTER_UTILITY_DURATION: 60,

  BASE_CRIT_CHANCE: 0.0,
  BASE_CRIT_MULT: 2.0,
  MAX_PERM_CRIT_CHANCE: 0.70,
  MAX_TOTAL_CRIT_CHANCE: 0.90,

  WAVE_BASE_ENEMIES: 7,
  WAVE_ENEMY_GROWTH: 1.25,
  WAVE_BOSS_INTERVAL: 3,

  BOOSTER_MIN_INTERVAL: 18,
  BOOSTER_RANDOM_CHANCE: 0.45,

  PICKUP_MAGNET_BASE: 100,
  PICKUP_MAGNET_PER_WAVE: 14,

  XP_PER_KILL: 8,
  XP_LEVEL_BASE: 40
};
